CREATE TABLE SENIORIDADE(
	ID INT NOT NULL,
	DESCRICAO VARCHAR(80) NOT NULL,
	CONSTRAINT PK_SENIORIDADE_ID PRIMARY KEY(ID)
);

CREATE TABLE TIPO_QUESTAO(
	ID INT NOT NULL,
	DESCRICAO VARCHAR(80) NOT NULL,
	CONSTRAINT PK_TIPO_QUESTAO_ID PRIMARY KEY(ID)
);